version: '3'

services:
  jupyterlab:
    image: jupyter/tensorflow-notebook
    container_name: lab
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: 1
